### ISSUE TITLE
Test "IdentityKeyPair.serialise" with objects from Node.js

### ISSUE THREAD

**Issue by bennyn** [wireapp/wire-webapp-cryptobox#78]
When an identity is created on a Node.js environment, then this identity cannot get serialized (CBOR is complaining about):

```js
RangeError: Wrong length!
    at validateArrayBufferArguments (D:\dev\projects\wireapp\wire-webapp-cryptobox\node_modules\core-js\modules\_typed-buffer.js:157:39)
    at new ArrayBuffer (D:\dev\projects\wireapp\wire-webapp-cryptobox\node_modules\core-js\modules\_typed-buffer.js:247:29)
    at Encoder.module.exports.Encoder._grow_buffer (D:\dev\projects\wireapp\wire-webapp-cryptobox\node_modules\wire-webapp-cbor\dist\commonjs\cbor\Encoder.js:23:17)
    at Encoder.module.exports.Encoder._ensure (D:\dev\projects\wireapp\wire-webapp-cryptobox\node_modules\wire-webapp-cbor\dist\commonjs\cbor\Encoder.js:33:19)
    at Encoder.module.exports.Encoder._write (D:\dev\projects\wireapp\wire-webapp-cryptobox\node_modules\wire-webapp-cbor\dist\commonjs\cbor\Encoder.js:41:12)
    at Encoder.module.exports.Encoder._u8 (D:\dev\projects\wireapp\wire-webapp-cryptobox\node_modules\wire-webapp-cbor\dist\commonjs\cbor\Encoder.js:74:19)
    at Encoder.module.exports.Encoder._write_type_and_len (D:\dev\projects\wireapp\wire-webapp-cryptobox\node_modules\wire-webapp-cbor\dist\commonjs\cbor\Encoder.js:50:21)
    at Encoder.module.exports.Encoder.object (D:\dev\projects\wireapp\wire-webapp-cryptobox\node_modules\wire-webapp-cbor\dist\commonjs\cbor\Encoder.js:328:19)
    at IdentityKey.module.exports.IdentityKey.encode (D:\dev\projects\wireapp\wire-webapp-cryptobox\node_modules\wire-webapp-proteus\dist\commonjs\proteus\keys\IdentityKey.js:47:9)
    at IdentityKeyPair.module.exports.IdentityKeyPair.encode (D:\dev\projects\wireapp\wire-webapp-cryptobox\node_modules\wire-webapp-proteus\dist\commonjs\proteus\keys\IdentityKeyPair.js:55:30)
    at IdentityKeyPair.module.exports.IdentityKeyPair.serialise (D:\dev\projects\wireapp\wire-webapp-cryptobox\node_modules\wire-webapp-proteus\dist\commonjs\proteus\keys\IdentityKeyPair.js:37:12)
    at File.save_identity (D:\dev\projects\wireapp\wire-webapp-cryptobox\dist\commonjs\store\File.js:49:22)
    at Object.it (D:\dev\projects\wireapp\wire-webapp-cryptobox\test\node\store\FileSpec.js:66:17)
    at attemptAsync (D:\dev\projects\wireapp\wire-webapp-cryptobox\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1980:24)
    at QueueRunner.run (D:\dev\projects\wireapp\wire-webapp-cryptobox\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1935:9)
    at QueueRunner.execute (D:\dev\projects\wireapp\wire-webapp-cryptobox\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1923:10)
```

Failing code:

```js
const identity = Proteus.keys.IdentityKeyPair.new();
identity.serialise();
```

**Comment by bennyn** [comment]
When running `node test.js`, this works fine:

**test.js**

```javascript
const Proteus = require('wire-webapp-proteus');

const identity = Proteus.keys.IdentityKeyPair.new();
const serialized = identity.serialise();
```

But when running the same withing a test suite (executed by `gulp test_node`), we get the following error:

```
RangeError: Wrong length!
    at validateArrayBufferArguments (D:\dev\projects\wireapp\wire-webapp-cryptobox\node_modules\core-js\modules\_typed-buffer.js:157:39)
    at new ArrayBuffer (D:\dev\projects\wireapp\wire-webapp-cryptobox\node_modules\core-js\modules\_typed-buffer.js:247:29)
    at Encoder.module.exports.Encoder._grow_buffer (D:\dev\projects\wireapp\wire-webapp-cryptobox\node_modules\wire-webapp-cbor\dist\commonjs\cbor\Encoder.js:23:17)
    at Encoder.module.exports.Encoder._ensure (D:\dev\projects\wireapp\wire-webapp-cryptobox\node_modules\wire-webapp-cbor\dist\commonjs\cbor\Encoder.js:33:19)
    at Encoder.module.exports.Encoder._write (D:\dev\projects\wireapp\wire-webapp-cryptobox\node_modules\wire-webapp-cbor\dist\commonjs\cbor\Encoder.js:41:12)
    at Encoder.module.exports.Encoder._u8 (D:\dev\projects\wireapp\wire-webapp-cryptobox\node_modules\wire-webapp-cbor\dist\commonjs\cbor\Encoder.js:74:19)
    at Encoder.module.exports.Encoder._write_type_and_len (D:\dev\projects\wireapp\wire-webapp-cryptobox\node_modules\wire-webapp-cbor\dist\commonjs\cbor\Encoder.js:50:21)
    at Encoder.module.exports.Encoder.object (D:\dev\projects\wireapp\wire-webapp-cryptobox\node_modules\wire-webapp-cbor\dist\commonjs\cbor\Encoder.js:328:19)
    at IdentityKey.encode (D:\dev\projects\wireapp\wire-webapp-cryptobox\node_modules\wire-webapp-proteus\dist\commonjs\proteus\keys\IdentityKey.js:59:7)
    at IdentityKeyPair.encode (D:\dev\projects\wireapp\wire-webapp-cryptobox\node_modules\wire-webapp-proteus\dist\commonjs\proteus\keys\IdentityKeyPair.js:74:27)
    at IdentityKeyPair.serialise (D:\dev\projects\wireapp\wire-webapp-cryptobox\node_modules\wire-webapp-proteus\dist\commonjs\proteus\keys\IdentityKeyPair.js:50:10)
    at Object.it (D:\dev\projects\wireapp\wire-webapp-cryptobox\test\node\store\FileSpec.js:59:26)
    at attemptSync (D:\dev\projects\wireapp\wire-webapp-cryptobox\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1950:24)
    at QueueRunner.run (D:\dev\projects\wireapp\wire-webapp-cryptobox\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1938:9)
    at QueueRunner.execute (D:\dev\projects\wireapp\wire-webapp-cryptobox\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1923:10)
    at Spec.queueRunnerFactory (D:\dev\projects\wireapp\wire-webapp-cryptobox\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:714:35)
```

The problematic piece is `this.public_key.encode(e)` within `IdentityKeyPair.encode`.

**Comment by bennyn** [comment]
Blocked by https://github.com/karma-runner/karma/issues/2631
